### ISSUE TITLE
Link to Pretrained model files mrefsr_gan.pth and mrefsr_mse.pth 

### ISSUE THREAD

**Issue by adrian-ash** [wdmwhh/MRefSR#2]
Hello,

Thanks for the great work. The results look amazing. I am working on a new benchmark for a paper and need the pretrained checkpoints  for mrefsr_gan.pth and mrefsr_mse.pth to test the model. The files located [here](https://github.com/wdmwhh/MRefSR/tree/test/experiments/pretrained_models) are just symlinks. Could you please provide a link?

I appreciate your prompt reply.

**Comment by wdmwhh** [comment]
Thank you for being interested.
First of all, I apologize for late replies. And you can get prompt reply if mailto zhanglin2019@ia.ac.cn  (Lin Zhang).

We have uploaded the model weights. Best Wishes.
