### ISSUE TITLE
对于文字部分有效果吗

### ISSUE THREAD

**Issue by Winnie202** [wdmwhh/MRefSR#3]
谢谢您的代码分享，请问，如果一张待超分的图像上有文字戳，当给予文字的参考图像，是否能有较好的效果？

**Comment by wdmwhh** [comment]
> Thank you for your code sharing, may I ask, if there is a text stamp on an image to be over-scored, when the reference image of the text is given, can it have a better effect?

I'm sorry for late replies. Thanks for your interesting idea. I previously tried to use 019.png in CUFED5 and utilize the alphabets of several fonts as reference images.  And I found that although some letters became clear, yet some letters turned wrong and some artifacts were introduced. As a result, it worked worse than text super-resolution methods that combined with classifiers.
