### ISSUE TITLE
could not open dataset website

### ISSUE THREAD

**Issue by yflv-yanxia** [wdmwhh/MRefSR#5]
could not open the dataset website, https://academictorrents.com/details/39424bb06d9172ac1c50fe4426eca51697bb4bfc

**Comment by wdmwhh** [comment]
感谢您对我们工作的关注。
目前数据集链接可以正常打开，如下图。
![image](https://github.com/wdmwhh/MRefSR/assets/38210459/2feb2ba3-ca32-44ca-85e0-970f192fc0fe)

**Comment by Grassyue** [comment]
你好，请问数据的网站你现在还可以打开吗？
