### ISSUE TITLE
in your code where is the Multi-Reference Attention Module and Spatial Aware Filtering Module

### ISSUE THREAD

**Issue by Nobody9966** [wdmwhh/MRefSR#7]

**Comment by wdmwhh** [comment]
I'm sorry for the late reply. 
The Multi-Reference Attention Module and Spatial Aware Filtering Module are contained within _Class MRAPAFusion_ in [ref_mrapa_restoration_arch.py](https://github.com/wdmwhh/MRefSR/blob/train/basicsr/archs/ref_mrapa_restoration_arch.py#L262). More specifically, Multi-Reference Attention Module is noted by "# multi-ref attention" while Spatial Aware Filtering Module is noted by "# spatial attention".
